spring:
  application:
    name: nz-companies-register
  
  datasource:
    url: jdbc:postgresql://localhost:5432/nz_companies_register
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false
  
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER:https://nz-companies-register.au.auth0.com/}
          jwk-set-uri: ${AUTH0_JWKS_URI:https://nz-companies-register.au.auth0.com/.well-known/jwks.json}
  
  cache:
    type: simple
    cache-names:
      - companies
      - directors
      - shareholders
      - search-results

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    nz.govt.companiesoffice: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

auth0:
  domain: ${AUTH0_DOMAIN:nz-companies-register.au.auth0.com}
  audience: ${AUTH0_AUDIENCE:https://api.companies-register.govt.nz}
  issuer: ${AUTH0_ISSUER:https://nz-companies-register.au.auth0.com/}

app:
  aws:
    region: ${AWS_REGION:ap-southeast-2}
    s3:
      document-bucket: ${S3_DOCUMENT_BUCKET:nz-companies-register-documents}
    dynamodb:
      document-table: ${DYNAMODB_DOCUMENT_TABLE:nz-companies-register-documents}
    sns:
      notification-topic: ${SNS_NOTIFICATION_TOPIC:nz-companies-register-notifications}
    sqs:
      notification-queue: ${SQS_NOTIFICATION_QUEUE:nz-companies-register-notifications}
  
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  
  business:
    annual-return:
      reminder-days: 30,7,0
      overdue-follow-up-days: 7,30
      strike-off-threshold-days: 180
    
    director:
      min-nz-au-residents: 1
    
    search:
      max-results: 100
      timeout-ms: 500